version: "3.9"

services:
  espnet:
    stdin_open: true
    tty: true
    image: dleongsh/espnet:202205-torch1.10-cu113-runtime
    deploy:
      resources:
        reservations:
          devices:
            # - driver: nvidia
              - capabilities: [gpu]
    volumes:
      - /home/digitalhub/Desktop/projects/datasets:/datasets
      - ./mount:/mount
      - ./models:/models
      - ./scripts:/scripts
      - ./mount/java:/workspace/espnet/egs2/java
      - ./mount/mt_test:/workspace/espnet/egs2/mt_test
      - ./mount/e2e_st:/workspace/espnet/egs2/e2e_st
      - ./nltk_data:/root/nltk_data
    ulimits:
      memlock: -1
      stack: 67108864
    shm_size: 16gb
    # command: bash -c "cd /mount/java/asr1 && ./run.sh"
    # command: bash -c "cd /mount/mt_test/mt1 && ./run.sh"
    # command: bash -c "cd /mount/cascade && ./run.sh"
    # command: bash -c "cd /mount/e2e_st/st1 && ./run.sh --local_run true"
  tensorboard:
    image: dleongsh/tensorboard:latest
    ports:
      - 6006:6006
    volumes:
      - ./mount:/mount
    command: tensorboard --logdir /mount --host 0.0.0.0 --port 6006
