version: "3.9"

services:
  espnet:
    stdin_open: true
    tty: true
    image: dleongsh/espnet:202205-torch1.10-cu113-runtime
    deploy:
      resources:
        reservations:
          devices:
            # - driver: nvidia
              - capabilities: [gpu]
    volumes:
      - ./mount:/mount
      - ./models:/models
      - ./datasets:/datasets
      - ./mount/java:/workspace/espnet/egs2/java
      - ./mount/multilingual:/workspace/espnet/egs2/multilingual
      - ./mount/test_pretrain_with_commonvoice:/workspace/espnet/egs2/test_pretrain_with_commonvoice
      - ./mount/test_pretrain_covost2:/workspace/espnet/egs2/test_pretrain_covost2
    ulimits:
      memlock: -1
      stack: 67108864
    shm_size: 16gb
    command: bash -c "cd /mount/java/asr1 && ./run.sh"
    # command: bash -c "ls"
  tensorboard:
    image: dleongsh/tensorboard:latest
    ports:
      - 6006:6006
    volumes:
      - ./mount:/mount
    command: tensorboard --logdir /mount --host 0.0.0.0 --port 6006
