# network architecture

# frontend related
frontend: default
frontend_conf:
    n_fft: 512
    win_length: 400
    hop_length: 160

# encoder related
encoder: transformer
encoder_conf:
    input_layer: conv2d
    num_blocks: 12
    linear_units: 2048
    dropout_rate: 0.1
    output_size: 256  # dimension of attention
    attention_heads: 4
    attention_dropout_rate: 0.0

# decoder related
decoder: transformer
decoder_conf:
    attention_heads: 4
    linear_units: 1024
    num_blocks: 6
    dropout_rate: 0.3
    positional_dropout_rate: 0.3
    self_attention_dropout_rate: 0.3
    src_attention_dropout_rate: 0.3
# decoder_conf:
#     input_layer: embed
#     num_blocks: 6
#     linear_units: 2048
#     dropout_rate: 0.1

extra_asr_decoder: transformer
extra_asr_decoder_conf:
    input_layer: embed
    num_blocks: 2
    linear_units: 2048
    dropout_rate: 0.1

extra_mt_decoder: transformer
extra_mt_decoder_conf:
    input_layer: embed
    num_blocks: 2
    linear_units: 2048
    dropout_rate: 0.1

# loss related
model_conf:
    asr_weight: 0.3
    mt_weight: 0.0
    mtlalpha: 1.0
    lsm_weight: 0.1
    length_normalized_loss: false

# # optimization related
# optim: adam
# accum_grad: 2
# grad_clip: 3
# max_epoch: 200
# patience: 20
# optim_conf:
#     lr: 2.5
#     # lr: 5
# scheduler: noamlr
# scheduler_conf:
#     model_size: 256
#     warmup_steps: 25000
optim: adam
optim_conf:
    lr: 0.003
    betas:
    - 0.9
    - 0.98
    eps: 0.000000001
    weight_decay: 0.0001
scheduler: warmuplr
scheduler_conf:
    warmup_steps: 10000


# minibatch related
batch_type: folded
batch_bins: 64

best_model_criterion:
-   - valid
    - acc
    - max
keep_nbest_models: 1

specaug: specaug
specaug_conf:
    apply_time_warp: true
    time_warp_window: 5
    time_warp_mode: bicubic
    apply_freq_mask: true
    freq_mask_width_range:
    - 0
    - 30
    num_freq_mask: 2
    apply_time_mask: true
    time_mask_width_range:
    - 0
    - 40
    num_time_mask: 2
    